// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bot-settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-settings.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-settings.patch').default>>>>
    }
    '/api/guilds/:guildId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guilds/[guildId]/index.get').default>>>>
    }
    '/api/guilds/:guildId/lvoice': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guilds/[guildId]/lvoice.patch').default>>>>
    }
    '/api/guilds/:guildId/settings': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guilds/[guildId]/settings.patch').default>>>>
    }
    '/api/users/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[userId].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[userId].patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}