// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2026, 5:04:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["G:/github/Lunaby/dashboard/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/plugins/**/*.{js,ts,mjs}","G:/github/Lunaby/dashboard/app/composables/**/*.{js,ts,mjs}","G:/github/Lunaby/dashboard/app/utils/**/*.{js,ts,mjs}","G:/github/Lunaby/dashboard/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/github/Lunaby/dashboard/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;