module.exports = {
    success: '<:lunaby_yes:1486937949839818862>',
    error: '<:lunaby_no:1486937890016460810>',
    warning: '⚠️',
    info: 'ℹ️',
    categories: {
        home: '🏠',
        aiCore: '🤖',
        core: '⚙️',
        moderation: '🛡️',
        social: '👥',
        system: '🔧',
        fun: '🎉',
        folder: '📁',
    },
    personalize: {
        info: '✏️',
        search: '🔍',
        memory: '🧠',
        manage: '📋',
        clear: '🗑️',
        importance: '⭐',
    },
    quota: {
        pro: '💬',
        vision: '🎨',
    },
    moderation: {
        ban: '🔨',
        unban: '🔓',
        kick: '👢',
        mute: '🔇',
        unmute: '🔊',
        warn: '⚠️',
        clearWarnings: '🧹',
    },
    lvoice: {
        createChannel: '➕',
        cooldown: '⏳',
    },
    image: {
        sparkle: '✨',
    },
    achievements: {
        unlocked: '🎉',
    },
    topgg: {
        vote: '🗳️',
        test: '🧪',
        pass: '✅',
        weekend: '🎉',
    },
    mal: {
        stats: '📊',
        info: '📝',
        score: '⭐',
        rank: '🏆',
        popularity: '❤️',
        users: '👥',
        episodes: '🎬',
        tv: '📺',
        status: '📅',
        tags: '🏷️',
        duration: '⌛',
        season: '🗓️',
        studio: '🏢',
        link: '🔗',
        volumes: '📚',
        chapters: '📑',
        author: '✍️',
    },
    gifActions: {
        pat: '🤗',
        hug: '🫂',
        slap: '👋',
        punch: '👊',
        kiss: '💋',
        poke: '👉',
    },
    progress: {
        empty: '⬛',
        thinking: '<:thinking:1050344785153626122>',
        wao: '<:wao:1050344773698977853>',
        bright: '🔆',
        fastForward: '⏭️',
        like: '<:like:1049784377103622218>',
    },
    locale: {
        crossMark: '❌',
        partyPopper: '🎉',
        user: '👤',
        id: '🆔',
        moderator: '👮',
        note: '📝',
        calendar: '📅',
        hourglass: '⏳',
        hammer: '🔨',
        boot: '👢',
        mute: '🔇',
        unmute: '🔊',
        warning: '⚠️',
        alert: '🚨',
        unban: '🔓',
        clipboard: '📋',
        stopwatch: '⏱️',
        settings: '⚙️',
        shield: '🛡️',
        bell: '🔔',
        monitor: '📡',
        books: '📚',
        wrench: '🔧',
        voice: '🎙️',
        folder: '📁',
        group: '👥',
        bitrate: '🔈',
        pencil: '✏️',
        search: '🔍',
        memory: '🧠',
        statusOn: '🟢',
        statusOff: '🔴',
        heart: '❤️',
        thought: '💭',
        stats: '📊',
        sparkle: '💫',
    },
};