module.exports = {
  DEFAULT_PREFIX: 'e.',
  DISCORD_MESSAGE_MAX_LENGTH: 2000,
  SUMMARY_MESSAGE_TRUNCATE_LENGTH: 150,
  MAX_CONVERSATION_LENGTH: 15,
  MAX_CONVERSATION_AGE_MS: 1 * 60 * 60 * 1000,
  RECENT_MEMORY_MESSAGES_COUNT: 5,
  RELEVANT_MEMORY_COUNT: 3,
  DETAILED_MEMORY_DISPLAY_COUNT: 15,
  DEFAULT_MEMORY_DISPLAY_COUNT: 3,
  AI_TIMEOUT_MS: 25000,
  API_REQUEST_TIMEOUT_MS: 120000,
  TYPING_INDICATOR_INTERVAL_MS: 5000,
  GUILD_DEPLOY_DELAY_MS: 1000,
  STREAM_UPDATE_INTERVAL_MS: 400,
  STREAM_MIN_CHUNK_SIZE: 20,
  STREAM_BATCH_UPDATE_SIZE: 150,
  STREAM_ENABLE_BY_DEFAULT: true,
  MEMORY_CACHE_EXPIRY_MS: 15 * 60 * 1000,
  QUOTA_PERIOD_DAYS: 30,
  DEFAULT_USER_MESSAGE_LIMIT: 600,
  UNLIMITED_QUOTA: -1,
  USER_ROLES: {
    OWNER: 'owner',
    ADMIN: 'admin',
    PRO: 'pro',
    USER: 'user'
  },
  ROLE_LIMITS: {
    owner: -1,
    admin: -1,
    pro: 100,
    user: 1
  },
  DEFAULT_USER_ID: 'anonymous-user',
  DEFAULT_LANGUAGE: 'vi',
  DEFAULT_COMMUNICATION_STYLE: 'friendly',
  DEFAULT_MODEL: 'lunaby-pro',
  DEFAULT_MAX_TOKENS: 2048,
  CODE_MAX_TOKENS: 4000,
  MEMORY_EXTRACTION_MAX_TOKENS: 500,
  MEMORY_EXTRACTION_TEMPERATURE: 0.3,
  MEMORY_CATEGORIES: {
    PREFERENCE: 'preference',
    FACT: 'fact',
    EVENT: 'event',
    ACHIEVEMENT: 'achievement'
  },
  MEMORY_SOURCES: {
    CONVERSATION: 'conversation',
    COMMAND: 'command',
    AUTO_EXTRACTED: 'auto-extracted',
    MANUAL: 'manual'
  },
  MIN_IMPORTANCE: 1,
  MAX_IMPORTANCE: 10,
  DEFAULT_IMPORTANCE: 5,
  HIGH_IMPORTANCE_THRESHOLD: 7,
  CONVERSATION_CLEANUP_INTERVAL_MS: 30 * 60 * 1000,
  COLLECTIONS: {
    CONVERSATIONS: 'conversations',
    CONVERSATION_META: 'conversation_meta',
    USER_PROFILES: 'user_profiles',
    USER_MEMORIES: 'user_memories',
    USER_QUOTAS: 'user_quotas',
    GUILDS: 'guilds',
    MONITOR_SETTINGS: 'monitor_settings',
    MONITOR_LOGS: 'monitor_logs'
  },
  SEVERITY_LEVELS: {
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high'
  },
  REQUEST_TYPES: {
    IMAGE: 'image',
    MEMORY: 'memory',
    CODE: 'code',
    CHAT: 'chat'
  },
  CHANNEL_TYPES: {
    DM: 'DM',
    GUILD_TEXT: 0
  },
  DISCORD_ERROR_CODES: {
    MISSING_PERMISSIONS: 50013
  }
};